### ISSUE TITLE
upstream ROS2 cv_bridge porting

### ISSUE THREAD

**Issue by gaoethan** [ros2/vision_opencv#12]
Hi, I have already finished the code and tests porting (https://github.com/gaoethan/vision_opencv/tree/ros2_cv_bridge/cv_bridge) of **cv_bridge** which is hosted within **vision_opencv** before, moreover, all the tests have already passed and I'll prepare to upstream it to benefit those ROS2 community users who need it while developing with OpenCV in the perception applications. So I'd like to check how to upstream it with you before the final PRs:

- Option 1: submit PR for this ROS2 branch of vision_opencv
- Option 2: create a separate project of ROS2 cv_bridge

please share your comments for your preference or another option if  both the above 2 options don't work, thanks !

**Comment by clalancette** [comment]
Personally, I think it would be best if you made a PR to this fork, and then we eventually merge it in here.  From there, we would need to coordinate with the maintainers of https://github.com/ros-perception/vision_opencv to see if they want to keep this forked version or merge as much as possible back into the real upstream, possibly on another branch.

**Comment by mikaelarguedas** [comment]
Nice work!

As this repository is used only for a set of demos and is not tested on all our platforms or actively maintained, I would recommend starting with option 3:
- contact the maintainers of `vision_opencv` to get a ros2 branch on their repository to host a ROS 2 version of the package.
  - Regardless of the maintainers' stand on the existence or maintenance of a ros2 branch, changes that are backward compatible (if any) should be submitted on the latest ROS 1 branch to minimize the diff between the ROS 1 and ROS 2 version.

As far as maintenance goes, I don't think any of us in the ros2 team has the bandwidth to take on additional packages. So it would require either getting the current ROS1 maintainers to buy-in maintaining both versions or you to commit to maintain it and/or find maintainers to help you with the task.

In the meantime I recommend advertising your package on the [ROS 2 discourse bulletin board thread](https://discourse.ros.org/t/ros-2-collaboration-bulletin-board/2239) so that ROS 2 users are aware of it and can use it / provide feedback.

Thanks again for your work!

**Comment by gaoethan** [comment]
@mikaelarguedas @clalancette thanks for your comments, so let me check with the original maintainer of vision_opencv firstly.

**Comment by gaoethan** [comment]
@clalancette @mikaelarguedas as you can see that I had checked with the original maintainer (a.k.a Vincent Rabaud) of [vision_opencv](https://github.com/ros-perception/vision_opencv), but there is no response and feedback up till now in the past 2 weeks and I assume that he doesn't buy-in to merge back this ros2 porting of cv_bridge for the time being, so I'd like to submit this porting under the umbrella of ros2 firstly and **I commit to maintain it**.  and I can transfer the maintaining to ros vision_opencv maintainer on condition that he want to involve to maintain the ros2 porting someday. 
next I want to check with you that whether I directly submit PRs to this [ros2 vision_opencv](https://github.com/ros2/vision_opencv) or separately maintain it in another ros2 project, both work for me and let's make the decision, thanks !

**Comment by gaoethan** [comment]
@ros2/team Any extra comments ? 😃 thanks !

**Comment by mikaelarguedas** [comment]
@gaoethan thanks for your patience on this.
I got confirmation from @vrabaud that he is willing to host the ported packages on a ros2 branch of the upstream repository and to give you write access to maintain the ros2 branch of that repository.
A ros2 branch [has been created ](https://github.com/ros-perception/vision_opencv/tree/ros2). And can now be used as a base branch for PRs targeting ROS2 support.

**Comment by gaoethan** [comment]
ok. thanks for your effort @mikaelarguedas 👍

**Comment by jzp1025** [comment]
@gaoethan hi , im having some confusions about the upstream of the ros2_cv_bridge . i found that the code is the same as branch knetic , so how can i use this code in ros2 . can i just use ament to build it ? 
thanks ! im looking forward to your answer XD !

**Comment by gaoethan** [comment]
@jzp1025 Do u use the right branch (a.k.a `ros2_cv_bridge`), you can see the following screenshot from my checking, it's different.

![image](https://user-images.githubusercontent.com/16472154/38712320-65378b02-3efd-11e8-8220-61bacb8e1e49.png)

**Comment by jzp1025** [comment]
@gaoethan hi , thanks a lot . i have succeeded in building the cv_bridge using ament . but i failed run the opencv_tests with the Error : "    from cv_bridge import CvBridge  ImportError: No module named 'cv_bridge' "  . could you help me solve the problem ?  thanks again !

**Comment by gaoethan** [comment]
@jzp1025 now the cv_bridge has already been formally migrated to host a [ros2 branch](https://github.com/ros-perception/vision_opencv/tree/ros2) underneath ros-perception and it's better continue all the work there, moreover, this thread has different topic with your issues. :) So thank you for your issue and could you please submit the current/future  issues there accordingly ? and this allow more people to get resolved when they meet this same issue, of course, we'll fix all the issue there accordingly. thanks a lot !

For your current issue, I think you can currently work around it with the following method:
Place you source code of cv_bridge with ros2 core but not the way of overlay and then build them again, it should work after that.

Next we'll fix the root cause there with after your issue moved there or you can contribute if you like. thanks !

I'd like close this thread, because I think it has already been achieved, and thanks for all your great support !
