### ISSUE TITLE
image_geometry_utest fails on windows debug

### ISSUE THREAD

**Issue by dhood** [ros2/vision_opencv#2]
(I enabled the issue tracker to post this, lmk if there was a reason it was disabled and I'll move this elsewhere)

This failed on a windows debug job last night.
http://ci.ros2.org/job/nightly_win_deb/454/testReport/junit/(root)/projectroot/image_geometry_utest/

```
Stacktrace

-- run_test.py: invoking following command in 'C:\J\workspace\nightly_win_deb\ws\src\ros2\vision_opencv\image_geometry':
 - C:/J/workspace/nightly_win_deb/ws/build/image_geometry/test/Debug/image_geometry-utest.exe --gtest_output=xml:C:/J/workspace/nightly_win_deb/ws/build/image_geometry/test_results/image_geometry/image_geometry-utest.gtest.xml
[==========] Running 6 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 6 tests from PinholeTest
[ RUN      ] PinholeTest.accessorsCorrect
[       OK ] PinholeTest.accessorsCorrect (0 ms)
[ RUN      ] PinholeTest.projectPoint
[       OK ] PinholeTest.projectPoint (2 ms)
[ RUN      ] PinholeTest.rectifyPoint
-- run_test.py: return code 3221226356
-- run_test.py: generate result file 'C:/J/workspace/nightly_win_deb/ws/build/image_geometry/test_results/image_geometry/image_geometry-utest.gtest.xml' with failed test
-- run_test.py: verify result file 'C:/J/workspace/nightly_win_deb/ws/build/image_geometry/test_results/image_geometry/image_geometry-utest.gtest.xml'
```

Do we know why, and is this a use case that is worth spending time fixing the tests for?

**Comment by clalancette** [comment]
Oh, yuck.  I hadn't seen that before in CI.  Let me take a quick look.

**Comment by dhood** [comment]
yeah, the CI doesn't test debug. it's just windows debug, it might not be worth fixing, but in that case we could consider disabling tests for that combination

**Comment by mikaelarguedas** [comment]
My guess is that enabling the issue tracker have been forgotten when the repo has been forked (forked repos have issue tracker disable by default)

**Comment by clalancette** [comment]
OK.  So, this is actually a problem.  Like some other things I've fixed recently, when running this under valgrind, there are a slew of errors about accessing uninitialized memory.  So we have just been getting lucky.  I'll see if I can fix these problems and open a PR.

**Comment by dirk-thomas** [comment]
I ran the failing test in the debugger ~~and the uninitialized variable was easy to identify. See ros-perception/vision_opencv#168 for the proposed fix upstream.~~

**Update:** nvm, the variable in question was fine but the function `cv::projectPoints` still raises an exception...

**Comment by clalancette** [comment]
Nice catch.  That bug is one of the reasons I like to have all my variables declared on separate lines.
